// -*- C++ -*-
#ifndef   CPPQEDCORE_QUANTUMOPERATOR_TRIDIAGONALHAMILTONIANFWD_H_INCLUDED
#define   CPPQEDCORE_QUANTUMOPERATOR_TRIDIAGONALHAMILTONIANFWD_H_INCLUDED

namespace quantumoperator {

template<int RANK, bool IS_TIME_DEPENDENT>
class TridiagonalHamiltonian;

} // quantumoperator

#endif // CPPQEDCORE_QUANTUMOPERATOR_TRIDIAGONALHAMILTONIANFWD_H_INCLUDED
