// -*- C++ -*-
#ifndef   QUANTUMOPERATOR_TRIDIAGONALHAMILTONIANFWD_H_INCLUDED
#define   QUANTUMOPERATOR_TRIDIAGONALHAMILTONIANFWD_H_INCLUDED

namespace quantumoperator {

template<int RANK, bool IS_TIME_DEPENDENT>
class TridiagonalHamiltonian;

} // quantumoperator

#endif // QUANTUMOPERATOR_TRIDIAGONALHAMILTONIANFWD_H_INCLUDED
