// -*- C++ -*-
#ifndef   BLITZ_ARRAY_LARGEST_RANK_H_INCLUDED
#define   BLITZ_ARRAY_LARGEST_RANK_H_INCLUDED

#ifndef   BLITZ_ARRAY_LARGEST_RANK
#define   BLITZ_ARRAY_LARGEST_RANK 11
#endif // BLITZ_ARRAY_LARGEST_RANK

#endif // BLITZ_ARRAY_LARGEST_RANK_H_INCLUDED
