// -*- C++ -*-
#ifndef   CUSTOMELEMENTSEXAMPLE_INTERACTIONS_PARTICLECAVITY_INTERFERENCEWORKAROUNDFWD_H_INCLUDED
#define   CUSTOMELEMENTSEXAMPLE_INTERACTIONS_PARTICLECAVITY_INTERFERENCEWORKAROUNDFWD_H_INCLUDED

namespace particlecavity_interferenceworkaround {

class InterferenceBase;

struct ParsInterferenceWorkaround;
} // particlecavity_interferenceworkaround

class Interference;

#endif // CUSTOMELEMENTSEXAMPLE_INTERACTIONS_PARTICLECAVITY_INTERFERENCEWORKAROUNDFWD_H_INCLUDED
