// -*- C++ -*-
#ifndef   MODE_FUNCTION_TYPE_FWD_INCLUDED
#define   MODE_FUNCTION_TYPE_FWD_INCLUDED

enum ModeFunctionType {MFT_SIN, MFT_COS, MFT_PLUS, MFT_MINUS};

#endif // MODE_FUNCTION_TYPE_FWD_INCLUDED
