// -*- C++ -*-
#ifndef   FREES_PUMPEDTWOLEVELATOMFWD_H_INCLUDED
#define   FREES_PUMPEDTWOLEVELATOMFWD_H_INCLUDED

class PumpedTwoLevelAtom   ;
class PumpedTwoLevelAtomSch;

#endif // FREES_PUMPEDTWOLEVELATOMFWD_H_INCLUDED
