// -*- C++ -*-
#ifndef   CPPQEDELEMENTS_UTILS_QM_PICTUREFWD_H_INCLUDED
#define   CPPQEDELEMENTS_UTILS_QM_PICTUREFWD_H_INCLUDED

enum QM_Picture {QMP_IP, QMP_UIP, QMP_SCH};

#endif // CPPQEDELEMENTS_UTILS_QM_PICTUREFWD_H_INCLUDED
