// -*- C++ -*-
#ifndef   UTILS_INCLUDE_IMPL_VECTORFROMMATRIXSLICEITERATOR_TCC_INCLUDED
#define   UTILS_INCLUDE_IMPL_VECTORFROMMATRIXSLICEITERATOR_TCC_INCLUDED

#include "VectorFromMatrixSliceIterator.h"

#include "impl/BlitzArraySliceIterator.tcc"

#endif // UTILS_INCLUDE_IMPL_VECTORFROMMATRIXSLICEITERATOR_TCC_INCLUDED