// -*- C++ -*-
#ifndef   ELEMENTS_COMPOSITE_COMPOSITENEWFWD_H_INCLUDED
#define   ELEMENTS_COMPOSITE_COMPOSITENEWFWD_H_INCLUDED

// template<int>
struct CompositeConsistencyException;



#endif // ELEMENTS_COMPOSITE_COMPOSITENEWFWD_H_INCLUDED
