// -*- C++ -*-
#ifndef   ELEMENTS_COMPOSITES_COMPOSITENEWFWD_H_INCLUDED
#define   ELEMENTS_COMPOSITES_COMPOSITENEWFWD_H_INCLUDED

// template<int>
struct CompositeConsistencyException;



#endif // ELEMENTS_COMPOSITES_COMPOSITENEWFWD_H_INCLUDED
