// -*- C++ -*-
#ifndef STRUCTURE_ELEMENTLIOUVILLEANAVERAGEDCOMMONFWD_H_INCLUDED
#define STRUCTURE_ELEMENTLIOUVILLEANAVERAGEDCOMMONFWD_H_INCLUDED

namespace structure {


template<typename BASE>
class ElementLiouvilleanAveragedCommon;

} // structure


#endif // STRUCTURE_ELEMENTLIOUVILLEANAVERAGEDCOMMONFWD_H_INCLUDED


