// -*- C++ -*-
#ifndef CPPQEDCORE_STRUCTURE_ELEMENTLIOUVILLEANAVERAGEDCOMMONFWD_H_INCLUDED
#define CPPQEDCORE_STRUCTURE_ELEMENTLIOUVILLEANAVERAGEDCOMMONFWD_H_INCLUDED

namespace structure {


template<typename BASE>
class ElementLiouvilleanAveragedCommon;

} // structure


#endif // CPPQEDCORE_STRUCTURE_ELEMENTLIOUVILLEANAVERAGEDCOMMONFWD_H_INCLUDED


