// -*- C++ -*-
#ifndef   STRUCTURE_TRIDIAGONALHAMILTONIANFWD_H_INCLUDED
#define   STRUCTURE_TRIDIAGONALHAMILTONIANFWD_H_INCLUDED

namespace structure {

template<int RANK, bool IS_TIME_DEPENDENT>
class TridiagonalHamiltonian;

} // structure

#endif // STRUCTURE_TRIDIAGONALHAMILTONIANFWD_H_INCLUDED
