// -*- C++ -*-
#ifndef   ELEMENTS_COMPOSITE_COMPOSITEFWD_H_INCLUDED
#define   ELEMENTS_COMPOSITE_COMPOSITEFWD_H_INCLUDED

// template<int>
struct CompositeConsistencyException;



#endif // ELEMENTS_COMPOSITE_COMPOSITEFWD_H_INCLUDED
