// Copyright András Vukics 2006–2020. Distributed under the Boost Software License, Version 1.0. (See accompanying file LICENSE.txt)
// -*- C++ -*-
#ifndef   CPPQEDELEMENTS_INTERACTIONS_GENERALDICKEFWD_H_INCLUDED
#define   CPPQEDELEMENTS_INTERACTIONS_GENERALDICKEFWD_H_INCLUDED

#endif // CPPQEDELEMENTS_INTERACTIONS_GENERALDICKEFWD_H_INCLUDED
