// -*- C++ -*-
#ifndef   CPPQEDELEMENTS_INTERACTIONS_GENERALDICKEFWD_H_INCLUDED
#define   CPPQEDELEMENTS_INTERACTIONS_GENERALDICKEFWD_H_INCLUDED

#endif // CPPQEDELEMENTS_INTERACTIONS_GENERALDICKEFWD_H_INCLUDED
