// -*- C++ -*-
#ifndef   CPPQEDELEMENTS_INTERACTIONS_IDENTICALPARTICLESFWD_H_INCLUDED
#define   CPPQEDELEMENTS_INTERACTIONS_IDENTICALPARTICLESFWD_H_INCLUDED


template<int NP> // number of particles
class IdenticalParticles;


#endif // CPPQEDELEMENTS_INTERACTIONS_IDENTICALPARTICLESFWD_H_INCLUDED
