// -*- C++ -*-
#ifndef   INTERACTIONS_MODECORRELATIONSFWD_H_INCLUDED
#define   INTERACTIONS_MODECORRELATIONSFWD_H_INCLUDED

class ModeCorrelations;

#endif // INTERACTIONS_MODECORRELATIONSFWD_H_INCLUDED
