// Copyright András Vukics 2006–2017. Distributed under the Boost Software License, Version 1.0. (See accompanying file LICENSE.txt)
#ifndef   CPPQEDELEMENTS_INTERACTIONS_MODECORRELATIONSFWD_H_INCLUDED
#define   CPPQEDELEMENTS_INTERACTIONS_MODECORRELATIONSFWD_H_INCLUDED

class ModeCorrelations;

#endif // CPPQEDELEMENTS_INTERACTIONS_MODECORRELATIONSFWD_H_INCLUDED
