// -*- C++ -*-
#ifndef   CPPQEDELEMENTS_INTERACTIONS_NX_COUPLEDMODESFWD_H_INCLUDED
#define   CPPQEDELEMENTS_INTERACTIONS_NX_COUPLEDMODESFWD_H_INCLUDED

namespace nxcoupledmodes {

template<bool IS_HA>
class Base;

} // nxcoupledmodes


#endif // CPPQEDELEMENTS_INTERACTIONS_NX_COUPLEDMODESFWD_H_INCLUDED
