// -*- C++ -*-
#ifndef   CPPQEDELEMENTS_INTERACTIONS_PARTICLETWOMODES_H_INCLUDED
#define   CPPQEDELEMENTS_INTERACTIONS_PARTICLETWOMODES_H_INCLUDED

#include "ParticleTwoModes_.h"

#include "ParticleCavity.h"

#endif // CPPQEDELEMENTS_INTERACTIONS_PARTICLETWOMODES_H_INCLUDED
