// -*- C++ -*-
#ifndef   CPPQEDCORE_UTILS_BOOLEANNEGATEDPROXYFWD_H_INCLUDED
#define   CPPQEDCORE_UTILS_BOOLEANNEGATEDPROXYFWD_H_INCLUDED

namespace cpputils {

class BooleanNegatedProxy;

} // cpputils

#endif // CPPQEDCORE_UTILS_BOOLEANNEGATEDPROXYFWD_H_INCLUDED
