// -*- C++ -*-
#ifndef   UTILS_INCLUDE_BOOLEANNEGATEDPROXYFWD_H_INCLUDED
#define   UTILS_INCLUDE_BOOLEANNEGATEDPROXYFWD_H_INCLUDED

namespace cpputils {

class BooleanNegatedProxy;

} // cpputils

#endif // UTILS_INCLUDE_BOOLEANNEGATEDPROXYFWD_H_INCLUDED
