// -*- C++ -*-
#ifndef   UTILS_DRIVENDAMPEDHARMONICOSCILLATORFWD_H_INCLUDED
#define   UTILS_DRIVENDAMPEDHARMONICOSCILLATORFWD_H_INCLUDED

class DrivenDampedHarmonicOscillator;

#endif // UTILS_DRIVENDAMPEDHARMONICOSCILLATORFWD_H_INCLUDED
