// Copyright András Vukics 2006–2020. Distributed under the Boost Software License, Version 1.0. (See accompanying file LICENSE.txt)
#ifndef   CPPQEDCORE_UTILS_DRIVENDAMPEDHARMONICOSCILLATORFWD_H_INCLUDED
#define   CPPQEDCORE_UTILS_DRIVENDAMPEDHARMONICOSCILLATORFWD_H_INCLUDED

class DrivenDampedHarmonicOscillator;

#endif // CPPQEDCORE_UTILS_DRIVENDAMPEDHARMONICOSCILLATORFWD_H_INCLUDED
