// -*- C++ -*-
#ifndef   CPPQEDCORE_UTILS_DRIVENDAMPEDHARMONICOSCILLATORFWD_H_INCLUDED
#define   CPPQEDCORE_UTILS_DRIVENDAMPEDHARMONICOSCILLATORFWD_H_INCLUDED

class DrivenDampedHarmonicOscillator;

#endif // CPPQEDCORE_UTILS_DRIVENDAMPEDHARMONICOSCILLATORFWD_H_INCLUDED
