// -*- C++ -*-
#ifndef   CPPQEDCORE_UTILS_MATHEXTENSIONSFWD_H_INCLUDED
#define   CPPQEDCORE_UTILS_MATHEXTENSIONSFWD_H_INCLUDED

namespace mathutils {

struct FactOverflow;

} // mathutils

#endif // CPPQEDCORE_UTILS_MATHEXTENSIONSFWD_H_INCLUDED
