// -*- C++ -*-
#ifndef   CPPQEDCORE_UTILS_MULTIINDEXITERATORFWD_H_INCLUDED
#define   CPPQEDCORE_UTILS_MULTIINDEXITERATORFWD_H_INCLUDED

namespace cpputils {

template<int>
class MultiIndexIterator;

} // cpputils

#endif // CPPQEDCORE_UTILS_MULTIINDEXITERATORFWD_H_INCLUDED
