// -*- C++ -*-
#ifndef   CPPQEDCORE_UTILS_VECTORFROMMATRIXSLICEITERATOR_TCC_INCLUDED
#define   CPPQEDCORE_UTILS_VECTORFROMMATRIXSLICEITERATOR_TCC_INCLUDED

#include "VectorFromMatrixSliceIterator.h"

#include "BlitzArraySliceIterator.tcc"

#endif // CPPQEDCORE_UTILS_VECTORFROMMATRIXSLICEITERATOR_TCC_INCLUDED