// -*- C++ -*-
#ifndef   QUANTUMTRAJECTORY_EVOLUTION_FWD_H_INCLUDED
#define   QUANTUMTRAJECTORY_EVOLUTION_FWD_H_INCLUDED

namespace evolution {
  
struct Pars;

} // evolution

#endif // QUANTUMTRAJECTORY_EVOLUTION_FWD_H_INCLUDED
