// -*- C++ -*-
#ifndef   CPPQEDCORE_QUANTUMTRAJECTORY_EVOLUTION_FWD_H_INCLUDED
#define   CPPQEDCORE_QUANTUMTRAJECTORY_EVOLUTION_FWD_H_INCLUDED

namespace evolution {
  
struct Pars;

} // evolution

#endif // CPPQEDCORE_QUANTUMTRAJECTORY_EVOLUTION_FWD_H_INCLUDED
