// -*- C++ -*-
#ifndef   DRIVEN_DAMPED_HARMONIC_OSCILLATOR_FWD_INCLUDED
#define   DRIVEN_DAMPED_HARMONIC_OSCILLATOR_FWD_INCLUDED

class DrivenDampedHarmonicOscillator;

#endif // DRIVEN_DAMPED_HARMONIC_OSCILLATOR_FWD_INCLUDED
