// -*- C++ -*-
#ifndef   CPPQEDCORE_QUANTUMDATA_DENSITYOPERATORFWD_H_INCLUDED
#define   CPPQEDCORE_QUANTUMDATA_DENSITYOPERATORFWD_H_INCLUDED


namespace quantumdata {


template<int>
class DensityOperator;


} // quantumdata


#endif // CPPQEDCORE_QUANTUMDATA_DENSITYOPERATORFWD_H_INCLUDED
