// -*- C++ -*-
#ifndef   CPPQEDCORE_QUANTUMDATA_DIMENSIONSBOOKKEEPERFWD_H_INCLUDED
#define   CPPQEDCORE_QUANTUMDATA_DIMENSIONSBOOKKEEPERFWD_H_INCLUDED

class DimensionalityMismatchException;

template<int RANK, bool IS_CONST=true>
class DimensionsBookkeeper;

#endif // CPPQEDCORE_QUANTUMDATA_DIMENSIONSBOOKKEEPERFWD_H_INCLUDED
