// -*- C++ -*-
#ifndef   CPPQEDCORE_QUANTUMDATA_NONORTHOGONALDENSITYOPERATORFWD_H_INCLUDED
#define   CPPQEDCORE_QUANTUMDATA_NONORTHOGONALDENSITYOPERATORFWD_H_INCLUDED

namespace quantumdata {

template<int RANK>
struct NonOrthogonalDensityOperator;


} // quantumdata

#endif // CPPQEDCORE_QUANTUMDATA_NONORTHOGONALDENSITYOPERATORFWD_H_INCLUDED
