// -*- C++ -*-
#ifndef   QUANTUMDATA_NONORTHOGONALDENSITYOPERATORFWD_H_INCLUDED
#define   QUANTUMDATA_NONORTHOGONALDENSITYOPERATORFWD_H_INCLUDED

namespace quantumdata {

template<int RANK>
struct NonOrthogonalDensityOperator;


} // quantumdata

#endif // QUANTUMDATA_NONORTHOGONALDENSITYOPERATORFWD_H_INCLUDED
