// -*- C++ -*-
#ifndef   CPPQEDCORE_QUANTUMDATA_NONORTHOGONALSTATEVECTORFWD_H_INCLUDED
#define   CPPQEDCORE_QUANTUMDATA_NONORTHOGONALSTATEVECTORFWD_H_INCLUDED

namespace quantumdata {

template<int RANK, typename TRAFO>
struct NonOrthogonalStateVector;


} // quantumdata

#endif // CPPQEDCORE_QUANTUMDATA_NONORTHOGONALSTATEVECTORFWD_H_INCLUDED
