// -*- C++ -*-
#ifndef QUANTUMTRAJECTORY_EVOLUTIONBINARY_H_INCLUDED
#define QUANTUMTRAJECTORY_EVOLUTIONBINARY_H_INCLUDED

#include "BinarySystem.h"

#include "Evolution.h"

#endif // QUANTUMTRAJECTORY_EVOLUTIONBINARY_H_INCLUDED
