// -*- C++ -*-
#ifndef QUANTUMTRAJECTORY_EVOLUTIONCOMPOSITE_H_INCLUDED
#define QUANTUMTRAJECTORY_EVOLUTIONCOMPOSITE_H_INCLUDED

#include "Composite.tcc"

#include "Evolution.h"

#endif // QUANTUMTRAJECTORY_EVOLUTIONCOMPOSITE_H_INCLUDED
