// -*- C++ -*-
#ifndef   ELEMENTS_FREES_PUMPEDTWOLEVELATOMFWD_H_INCLUDED
#define   ELEMENTS_FREES_PUMPEDTWOLEVELATOMFWD_H_INCLUDED

class PumpedTwoLevelAtom   ;
class PumpedTwoLevelAtomSch;

#endif // ELEMENTS_FREES_PUMPEDTWOLEVELATOMFWD_H_INCLUDED
