// -*- C++ -*-
#ifndef   ELEMENTS_FREES_TIMEINDEPENDENTMATRIXHAMILTONIANFWD_H_INCLUDED
#define   ELEMENTS_FREES_TIMEINDEPENDENTMATRIXHAMILTONIANFWD_H_INCLUDED

class MatrixNotSquareException;

class TimeIndependentMatrixHamiltonian;

template<int RANK, bool IS_TIME_DEPENDENT>
class TimeIndependentMatrixHamiltonianAveraged;


#endif // ELEMENTS_FREES_TIMEINDEPENDENTMATRIXHAMILTONIANFWD_H_INCLUDED
