// -*- C++ -*-
#ifndef   CPPQEDELEMENTS_FREES_BICHROMATICMODEFWD_H_INCLUDED
#define   CPPQEDELEMENTS_FREES_BICHROMATICMODEFWD_H_INCLUDED

#include "Mode_Fwd.h"

template<bool TEMPERATURE=false, typename A=mode::Averaged>
class BichromaticMode;

#endif // CPPQEDELEMENTS_FREES_BICHROMATICMODEFWD_H_INCLUDED
