// -*- C++ -*-
#ifndef   CPPQEDELEMENTS_FREES_PUMPEDTWOLEVELATOMFWD_H_INCLUDED
#define   CPPQEDELEMENTS_FREES_PUMPEDTWOLEVELATOMFWD_H_INCLUDED

class PumpedTwoLevelAtom   ;
class PumpedTwoLevelAtomSch;

#endif // CPPQEDELEMENTS_FREES_PUMPEDTWOLEVELATOMFWD_H_INCLUDED
