// -*- C++ -*-
#ifndef   CPPQEDELEMENTS_FREES_TIMEINDEPENDENTMATRIXHAMILTONIANFWD_H_INCLUDED
#define   CPPQEDELEMENTS_FREES_TIMEINDEPENDENTMATRIXHAMILTONIANFWD_H_INCLUDED

class MatrixNotSquareException;

class TimeIndependentMatrixHamiltonian;

template<int RANK>
class TimeIndependentMatrixHamiltonianAveraged;


#endif // CPPQEDELEMENTS_FREES_TIMEINDEPENDENTMATRIXHAMILTONIANFWD_H_INCLUDED
