// -*- C++ -*-
#ifndef   UTILS_INCLUDE_DRIVENDAMPEDHARMONICOSCILLATORFWD_H_INCLUDED
#define   UTILS_INCLUDE_DRIVENDAMPEDHARMONICOSCILLATORFWD_H_INCLUDED

class DrivenDampedHarmonicOscillator;

#endif // UTILS_INCLUDE_DRIVENDAMPEDHARMONICOSCILLATORFWD_H_INCLUDED
