// -*- C++ -*-
#ifndef   ELEMENTS_UTILS_QM_PICTUREFWD_H_INCLUDED
#define   ELEMENTS_UTILS_QM_PICTUREFWD_H_INCLUDED

enum QM_Picture {QMP_IP, QMP_UIP, QMP_SCH};

#endif // ELEMENTS_UTILS_QM_PICTUREFWD_H_INCLUDED
