// -*- C++ -*-
#ifndef   ELEMENTS_INTERACTIONS_MODECORRELATIONSFWD_H_INCLUDED
#define   ELEMENTS_INTERACTIONS_MODECORRELATIONSFWD_H_INCLUDED

class ModeCorrelations;

#endif // ELEMENTS_INTERACTIONS_MODECORRELATIONSFWD_H_INCLUDED
