// -*- C++ -*-
#ifndef   ELEMENTS_INTERACTIONS_IDENTICALPARTICLESFWD_H_INCLUDED
#define   ELEMENTS_INTERACTIONS_IDENTICALPARTICLESFWD_H_INCLUDED


template<int NP> // number of particles
class IdenticalParticles;


#endif // ELEMENTS_INTERACTIONS_IDENTICALPARTICLESFWD_H_INCLUDED
