// -*- C++ -*-
#ifndef   ELEMENTS_INTERACTIONS_NX_COUPLEDMODESFWD_H_INCLUDED
#define   ELEMENTS_INTERACTIONS_NX_COUPLEDMODESFWD_H_INCLUDED

namespace nxcoupledmodes {

template<bool IS_HA>
class Base;

} // nxcoupledmodes


#endif // ELEMENTS_INTERACTIONS_NX_COUPLEDMODESFWD_H_INCLUDED
