// -*- C++ -*-
#ifndef   ELEMENTS_INTERACTIONS_PARTICLETWOMODES_H_INCLUDED
#define   ELEMENTS_INTERACTIONS_PARTICLETWOMODES_H_INCLUDED

#include "ParticleTwoModes_.h"

#include "ParticleCavity.h"

#endif // ELEMENTS_INTERACTIONS_PARTICLETWOMODES_H_INCLUDED
