// -*- C++ -*-
#ifndef   CPPQEDCORE_COMPOSITES_COMPOSITEFWD_H_INCLUDED
#define   CPPQEDCORE_COMPOSITES_COMPOSITEFWD_H_INCLUDED

// template<int>
struct CompositeConsistencyException;



#endif // CPPQEDCORE_COMPOSITES_COMPOSITEFWD_H_INCLUDED
